-- MySQL Script generated by MySQL Workbench
-- Sun Apr 18 22:44:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Normaliseren_opdracht
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Normaliseren_opdracht` ;

-- -----------------------------------------------------
-- Schema Normaliseren_opdracht
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Normaliseren_opdracht` DEFAULT CHARACTER SET utf8 ;
USE `Normaliseren_opdracht` ;

-- -----------------------------------------------------
-- Table `Normaliseren_opdracht`.`Klant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Normaliseren_opdracht`.`Klant` ;

CREATE TABLE IF NOT EXISTS `Normaliseren_opdracht`.`Klant` (
  `klantid` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefoonnmr` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `huisnummer` INT NOT NULL,
  PRIMARY KEY (`klantid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Normaliseren_opdracht`.`Bestelling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Normaliseren_opdracht`.`Bestelling` ;

CREATE TABLE IF NOT EXISTS `Normaliseren_opdracht`.`Bestelling` (
  `bestelid` INT NOT NULL AUTO_INCREMENT,
  `klantid` INT NOT NULL,
  `totaal` INT NOT NULL,
  PRIMARY KEY (`bestelid`, `klantid`),
  INDEX `fk_bestelling_klantid_idx` (`klantid` ASC),
  CONSTRAINT `fk_bestelling_klantid`
    FOREIGN KEY (`klantid`)
    REFERENCES `Normaliseren_opdracht`.`Klant` (`klantid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Normaliseren_opdracht`.`Bestelregel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Normaliseren_opdracht`.`Bestelregel` ;

CREATE TABLE IF NOT EXISTS `Normaliseren_opdracht`.`Bestelregel` (
  `bestelid` INT NOT NULL,
  `productid` INT NOT NULL,
  `aantal` INT NOT NULL,
  PRIMARY KEY (`bestelid`, `productid`),
  CONSTRAINT `fk_Bestelregel_bestelid`
    FOREIGN KEY (`bestelid`)
    REFERENCES `Normaliseren_opdracht`.`Bestelling` (`bestelid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
